name: CI (global trustify CI)

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_call:
  merge_group:

concurrency:
  group: ci-global-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload-for-global-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: save trustify-ui image
        run: |
          docker build . -t ghcr.io/trustification/trustify-ui:pr-test -f Dockerfile
          docker save -o /tmp/trustify-ui.tar ghcr.io/trustification/trustify-ui:pr-test

      - name: Upload trustify-ui image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trustify-ui
          path: /tmp/trustify-ui.tar
          retention-days: 1

  run-global-ci:
    needs: build-and-upload-for-global-ci
    uses: trustification/trustify-ci/.github/workflows/global-ci.yml@main
    with:
      artifact: trustify-ui
      ui_image: ghcr.io/trustification/trustify-ui:pr-test
      run_api_tests: false
